version: '3'

services:
  postgresql:
    image: postgres
    container_name: lesson
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=lesson
      - POSTGRES_PASSWORD=lesson
      - POSTGRES_DATABASE=lesson
    command: postgres
    restart: always

#  mysql:
#    image: mysql:5.7
#    command: --max_allowed_packet=92505856
#    ports:
#      - 13306:3306
#    environment:
#      MYSQL_DATABASE: lesson
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - ./data/mysql:/var/lib/mysql
#      - ./data:/data
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    ports:
#      - 4000:80
#    links:
#      - mysql
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#      UPLOAD_LIMIT: 3000000000

  redis:
    image: redis:alpine3.14
    container_name: redis-lesson
    ports:
      - '6379-6379'
